# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ppv.v1 import ppv_pb2 as ppv_dot_v1_dot_ppv__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ppv/v1/ppv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PPVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestCompute = channel.unary_unary(
                '/ppv.v1.PPVService/RequestCompute',
                request_serializer=ppv_dot_v1_dot_ppv__pb2.ComputeRequest.SerializeToString,
                response_deserializer=ppv_dot_v1_dot_ppv__pb2.ComputeResponse.FromString,
                _registered_method=True)
        self.WaitCompute = channel.unary_stream(
                '/ppv.v1.PPVService/WaitCompute',
                request_serializer=ppv_dot_v1_dot_ppv__pb2.WaitRequest.SerializeToString,
                response_deserializer=ppv_dot_v1_dot_ppv__pb2.ComputeStatus.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/ppv.v1.PPVService/ListJobs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ppv_dot_v1_dot_ppv__pb2.JobList.FromString,
                _registered_method=True)
        self.RequestDot = channel.unary_unary(
                '/ppv.v1.PPVService/RequestDot',
                request_serializer=ppv_dot_v1_dot_ppv__pb2.DotRequest.SerializeToString,
                response_deserializer=ppv_dot_v1_dot_ppv__pb2.DotResponse.FromString,
                _registered_method=True)
        self.WaitDot = channel.unary_stream(
                '/ppv.v1.PPVService/WaitDot',
                request_serializer=ppv_dot_v1_dot_ppv__pb2.WaitRequest.SerializeToString,
                response_deserializer=ppv_dot_v1_dot_ppv__pb2.DotStatus.FromString,
                _registered_method=True)


class PPVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestCompute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitCompute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitDot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PPVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestCompute': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCompute,
                    request_deserializer=ppv_dot_v1_dot_ppv__pb2.ComputeRequest.FromString,
                    response_serializer=ppv_dot_v1_dot_ppv__pb2.ComputeResponse.SerializeToString,
            ),
            'WaitCompute': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitCompute,
                    request_deserializer=ppv_dot_v1_dot_ppv__pb2.WaitRequest.FromString,
                    response_serializer=ppv_dot_v1_dot_ppv__pb2.ComputeStatus.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ppv_dot_v1_dot_ppv__pb2.JobList.SerializeToString,
            ),
            'RequestDot': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDot,
                    request_deserializer=ppv_dot_v1_dot_ppv__pb2.DotRequest.FromString,
                    response_serializer=ppv_dot_v1_dot_ppv__pb2.DotResponse.SerializeToString,
            ),
            'WaitDot': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitDot,
                    request_deserializer=ppv_dot_v1_dot_ppv__pb2.WaitRequest.FromString,
                    response_serializer=ppv_dot_v1_dot_ppv__pb2.DotStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ppv.v1.PPVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ppv.v1.PPVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PPVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestCompute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppv.v1.PPVService/RequestCompute',
            ppv_dot_v1_dot_ppv__pb2.ComputeRequest.SerializeToString,
            ppv_dot_v1_dot_ppv__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitCompute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ppv.v1.PPVService/WaitCompute',
            ppv_dot_v1_dot_ppv__pb2.WaitRequest.SerializeToString,
            ppv_dot_v1_dot_ppv__pb2.ComputeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppv.v1.PPVService/ListJobs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ppv_dot_v1_dot_ppv__pb2.JobList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppv.v1.PPVService/RequestDot',
            ppv_dot_v1_dot_ppv__pb2.DotRequest.SerializeToString,
            ppv_dot_v1_dot_ppv__pb2.DotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitDot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ppv.v1.PPVService/WaitDot',
            ppv_dot_v1_dot_ppv__pb2.WaitRequest.SerializeToString,
            ppv_dot_v1_dot_ppv__pb2.DotStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
